### ISSUE TITLE
HttpCanary with parallel space 

### ISSUE THREAD

**Issue by sbn1413** [MegatronKing/HttpCanary#100]
I was installed parallel space through httpCanary setting option. But when I try to open it vai patallel space It showing error failed to open. I also attached the error image. I am using naugot version 7.1. Infinix note 4 is my device. 
![Screenshot_20200326-191748](https://user-images.githubusercontent.com/62733056/77716460-418a8a80-7004-11ea-9ce1-0f993fb7f77c.png)
 kindly check and give me a good solution. Thank you.

**Comment by tennc** [comment]
You open the parallel space app separately and see if it works? @sbn1413

**Comment by MegatronKing** [comment]
Use Parallel Space to open target captured app rather than HttpCanary.
