### ISSUE TITLE
抓的原始包是否都可以导出,或直接上传服务器

### ISSUE THREAD

**Issue by yelena-gaga** [MegatronKing/HttpCanary#101]
抓的原始包是否都可以导出,包括post包及post内容,或数据包直接上传服务器.
因为hcy格式导出后无法分析,查看包具体内容.

**Comment by tennc** [comment]
这个可以有，如果能支持wireshark 查看更好~
或者 httpcanary 再出个 pc版的？

**Comment by MegatronKing** [comment]
> 抓的原始包是否都可以导出,包括post包及post内容,或数据包直接上传服务器.
> 因为hcy格式导出后无法分析,查看包具体内容.

下个版本会支持批量保存，保存的格式会更加通用和直观

**Comment by MegatronKing** [comment]
> 这个可以有，如果能支持wireshark 查看更好~
> 或者 httpcanary 再出个 pc版的？

理论上可以实现导出pcap格式，用wireshark查看。但是因为HttpCanary关注的核心是应用层协议而不是传输层协议，所以这个支持起来工作量比较大。另外，PC端工具已经非常成熟了，我是肯定不会做的。

**Comment by MegatronKing** [comment]
IP->Transport->Application层级的原始包不打算支持，tcpdump本身就可以完成。批量保存的功v3.3.1已上线，如有问题，可以提出建议和反馈。
