### ISSUE TITLE
app筛选功能增强一点

### ISSUE THREAD

**Issue by bergyu** [MegatronKing/HttpCanary#11]
目前app筛选只有白名单功能，就是加多少应用，就只对加入的应用抓包，能不能从两个方面增强一点呢？
1，应用加入，希望有个多选批量加入的功能
2，目前是白名单，希望有个黑名单模式，就是除了黑名单之外的，都抓包，并且，能在已抓包的记录里面，长按能加入黑名单

**Comment by huitc** [comment]
https://github.com/MegatronKing/HttpCanary/issues/7#issuecomment-477037640
