### ISSUE TITLE
/HttpCanary/plugins/StatsOverview 没找到。

### ISSUE THREAD

**Issue by rantianhua** [MegatronKing/HttpCanary#116]
希望 StatsOverview 的地址能说得更清楚一些，无论是根目录下还是 APP 的内存存储都没法找到这个文件，全局搜索也找不到。

**Comment by MegatronKing** [comment]
完整路径应该是/sdcard/HttpCanary/plugins/StatsOverview。完成一次完整的抓包流程且抓到HTTP协议的包才会有（关闭抓包后保存文件）。
