### ISSUE TITLE
HttpCanary 无法在平行空间中打开

### ISSUE THREAD

**Issue by rantianhua** [MegatronKing/HttpCanary#117]
平行空间是在 HttpCanary 中下载安装的。

**Comment by MegatronKing** [comment]
为什么要在平行空间中打开HttpCanary？

**Comment by qinyang1018** [comment]
@MegatronKing  通过软件安装得平行空间，在miui12中无法打开，打开后闪退。 下载新版平行空间，空间，平行空间被代理后，空间内程序因限制代理不能正常进入应用。

**Comment by MegatronKing** [comment]
@qinyang1018 只能建议root设备了
