### ISSUE TITLE
是否可以把过滤的结果POST到指定的地址

### ISSUE THREAD

**Issue by qiacoucc** [MegatronKing/HttpCanary#12]
是否可以把过滤的结果POST到指定的地址, 可以自定义一个key ,post到自己的平台

**Comment by Barbery** [comment]
+1

**Comment by MegatronKing** [comment]
v2.11.5已上线相关插件

**Comment by qiacoucc** [comment]
> v2.11.5已上线相关插件

什么插件?

**Comment by qiacoucc** [comment]
上传的是zip文件 很不好服务器端进行分析,能否按照关键词,进行自定义POST上传的数据 最好是以字段形式POST过去 ,服务端就可以自行整理抓包数据
 
------------------ Original ------------------
