### ISSUE TITLE
Wiki page里指向的文档链接失效了吗？

### ISSUE THREAD

**Issue by alisen39** [MegatronKing/HttpCanary#122]
[https://github.com/MegatronKing/HttpCanary/tree/master/docs/v2/zh-CN](https://github.com/MegatronKing/HttpCanary/tree/master/docs/v2/zh-CN) 现在点击这个页面变成404了

**Comment by MegatronKing** [comment]
文档改成gitbook了，旧版的已失效。
https://github.com/MegatronKing/HttpCanary/blob/master/tutorials/zh-hans/README.md
