### ISSUE TITLE
Extend HTTPCanary with an ssl unpinning xposed module

### ISSUE THREAD

**Issue by yoshimo** [MegatronKing/HttpCanary#128]
Fighting SSL Pinning for analysis reasons is becoming more and more difficult for the interested user.
Frida /Objection as well as patching apks is not for the faint hearted.

https://github.com/Fuzion24/JustTrustMe is becoming outdated and people are getting more creative by implementing their own pinning methods.

It would be a perfect addition to this tool if you would supply a maintained xposed module or root module that takes on the challenge of unpinning even the self created pins. Modifying their native libs in memory and more.

**Comment by MegatronKing** [comment]
Network communication security is becoming more and more unbreakable, and I have no intention to fight them. In my original intention, HttpCanary is a debugging tool, not a cracking tool.

**Comment by yoshimo** [comment]
Cracking is such a hard word, it  is quite useful for looking at privacy leaks and helps to foster interoperability.
It would have been a nice premium feature addition for data privacy analysists @MegatronKing
