### ISSUE TITLE
请问关于Android中 Https 的包内容如何解析,目前自己用NetBare接收过来`解析全是乱码

### ISSUE THREAD

**Issue by vinciii** [MegatronKing/HttpCanary#129]
请问关于Android中 Https 的包内容如何解析,目前自己用NetBare接收过来`解析全是乱码

**Comment by MegatronKing** [comment]
SSL/TLS数据包是加密的，需要用中间人方式握手解密。原理参考我的这篇博客：https://juejin.im/post/5cc313755188252d6f11b463
