### ISSUE TITLE
64 bits support

### ISSUE THREAD

**Issue by LuisUrrutia** [MegatronKing/HttpCanary#13]
Some apps need parallel space 64bit support and when it's installed, the app opens but the traffic isn't recorded

**Comment by huitc** [comment]
https://apkpure.com/parallel-space-64bit-support/com.lbe.parallel.intl.arm64/versions

**Comment by huitc** [comment]
you can try installing an older version

**Comment by MegatronKing** [comment]
@LuisUrrutia v1.0.3037 is ok, try this https://apkpure.com/parallel-space-64bit-support/com.lbe.parallel.intl.arm64/download/15-APK?from=versions%2Fversion

**Comment by MegatronKing** [comment]
I will add the 64bit installation support in next version.

**Comment by MegatronKing** [comment]
Released on v2.9.1

**Comment by arsalan123ahmed** [comment]
Megatron your files are not installing
