### ISSUE TITLE
小米8Lite安装CA证书后,点击抓包无响应

### ISSUE THREAD

**Issue by ckingcc** [MegatronKing/HttpCanary#14]
小米8 lite 点击抓包按钮 出现无响应的结果

**Comment by MegatronKing** [comment]
可能是VPN启动不了，重启下手机试试，如果还是不行回复下，我再想想其它办法

**Comment by huitc** [comment]
我之前也试过 可以是其他app在连vpn
你开了之后关了再开 重复就行 (我是这样弄的😆

**Comment by ckingcc** [comment]
解决了
点击抓包按钮没有反应 需要后台去清理数据,然后再进就行了.
