### ISSUE TITLE
 互联网错误

### ISSUE THREAD

**Issue by jelly88893333** [MegatronKing/HttpCanary#16]
当我打开捕获时我得到一个互联网错误，这发生在很多应用程序中，但不是在所有应用程序上

**Comment by huitc** [comment]
https://github.com/MegatronKing/HttpCanary/tree/master/zh-CN

**Comment by MegatronKing** [comment]
@jelly88893333 请参考：https://juejin.im/post/5cc313755188252d6f11b463

**Comment by MegatronKing** [comment]
非HttpCanary问题，关闭此issue，如有需要再重新打开。
