### ISSUE TITLE
希望能夠加入app篩選功能

### ISSUE THREAD

**Issue by huitc** [MegatronKing/HttpCanary#2]
但希望不會因为app太多而崩潰 (加載列表?

**Comment by MegatronKing** [comment]
Did you try Settings -> APP Whitelist?

**Comment by huitc** [comment]
你不是中國人？...

**Comment by MegatronKing** [comment]
哈，抱歉，确实是。你可以试试设置—>应用白名单，抓指定的应用。

**Comment by huitc** [comment]
但。。有一点不方便。。。
弄到首页去？

**Comment by MegatronKing** [comment]
OK，这个我规划一下，首页和侧滑菜单栏入口现在有点多

**Comment by huitc** [comment]
收費的?.............. == @@

**Comment by MegatronKing** [comment]
基础功能都是免费的，部分进阶的功能是付费版本的，但是都有14天的试用期。这个App只有我一个人在开发，希望各位能支持一下，把App越做越好。如果无法支付付费版本或者囊中羞涩等，都可以邮件或者微信我，我可以无偿提供付费版本。

**Comment by huitc** [comment]
想问一下一定要装平行xx才能抓https 还是？

**Comment by MegatronKing** [comment]
1. 7.0以下版本手机不需要；
2. App的targetSDKVersion < 24不需要；
3. App的manifest中配置了信任自签证书不需要；
4. Root的手机把HttpCanary证书导入/ect/security/cacerts/里面，则不需要；

**Comment by huitc** [comment]
![IMG_20190324_154127](https://user-images.githubusercontent.com/20995449/54876473-6f664d80-4e4b-11e9-8dd0-ed08446e3935.jpg)
这种情況也行？

**Comment by MegatronKing** [comment]
targetSDKVersion < 24 的时候系统不会校验证书链，允许连接；反之如果服务端是自签证书就会报这种错。

**Comment by huitc** [comment]
所以平行xx能抓上述https包？😅

**Comment by huitc** [comment]
还有怎樣指定某一个/多个app?

**Comment by MegatronKing** [comment]
设置—>应用白名单

**Comment by huitc** [comment]
放在「高级搜索」里行么。。。

**Comment by huitc** [comment]
> 如果无法支付付费版本或者囊中羞涩等，都可以邮件或者微信我，我可以无偿提供付费版本。
我也不想白白拿走你的成品 不如这样 到我貢獻足夠多的时候你才给我😃

**Comment by huitc** [comment]
你看行不

**Comment by huitc** [comment]
还有经测试 用平行xx也不行。。。(证書问题
