### ISSUE TITLE
Stop suddenly When changing phone language to Arabic

### ISSUE THREAD

**Issue by ashraf20078** [MegatronKing/HttpCanary#30]
The application Stop suddenly When changing phone language to Arabic.
But it's Working very good when Phone language is English.

**Comment by MegatronKing** [comment]
A known issue, not supported when the language is from right to left.

**Comment by ashraf20078** [comment]
Is there a solution to this problem?  .. I liked this application a lot .. Please find a solution to this problem please .. Did you will resolve this problem in next updates?

**Comment by MegatronKing** [comment]
Fixed on v3.1.3

**Comment by ashraf20078** [comment]
> Fixed on v3.1.3

Thank You Very Much .. I tested it and now is working Very Good . You Are Amazing .
