### ISSUE TITLE
希望加入gzip解压功能

### ISSUE THREAD

**Issue by guochengli** [MegatronKing/HttpCanary#31]
希望在“抓包内容->文本解密”中加入 gzip -d 功能。我遇到的情况是：抓到的http包的content是经过gzip压缩后传输的。

**Comment by MegatronKing** [comment]
gzip默认是支持的，如果有发现未解析的数据包，可以邮件给我进行分析

**Comment by MegatronKing** [comment]
没有回复，暂时关闭。
