### ISSUE TITLE
JSON beautifier

### ISSUE THREAD

**Issue by LashooN** [MegatronKing/HttpCanary#32]
Feature: beautify the JSON, so its easier to  
read .

**Comment by MegatronKing** [comment]
Now has the beautified JSON.

**Comment by yoshimo** [comment]
For me this seems to fail.
application/json; charset=UTF-8
in the headers still give me a wall of text on zhe text tab that is hars to read and the preview either has nothing (not applicable) or splits it in two lines where the second one is awfully long.
https://beautifier.io/ does a better job at it
