### ISSUE TITLE
希望后续可以支持 Brotli 解码

### ISSUE THREAD

**Issue by 0wQ** [MegatronKing/HttpCanary#37]
目前使用 br 压缩的站点还是很多的，希望可以添加支持。

**Comment by MegatronKing** [comment]
@0wQ 可以的，能提供下case给我吗，我做下测试。

**Comment by 0wQ** [comment]
@MegatronKing 

Brotli: ``curl -H "accept-encoding:br" "https://api.mizore.cn/pi.txt" -v``
Gzip: ``curl -H "accept-encoding:gzip" "https://api.mizore.cn/pi.txt" -v``

**Comment by MegatronKing** [comment]
v2.11.10已支持
