### ISSUE TITLE
root了并且装的有xposed也不能用吗？

### ISSUE THREAD

**Issue by tanranran** [MegatronKing/HttpCanary#4]

**Comment by MegatronKing** [comment]
不root也可以用，你说的不能用是指？

**Comment by tanranran** [comment]
@MegatronKing 不想用VirtualApp的方式

**Comment by MegatronKing** [comment]
可以。参考用户手册2.4：https://github.com/MegatronKing/HttpCanary/tree/master/docs/v1/zh-CN#24-%E5%B0%86httpcanary%E6%A0%B9%E8%AF%81%E4%B9%A6%E6%B7%BB%E5%8A%A0%E5%88%B0%E7%B3%BB%E7%BB%9F%E4%BF%A1%E4%BB%BB%E8%AF%81%E4%B9%A6%E7%9B%AE%E5%BD%95%E9%9C%80root

**Comment by huitc** [comment]
ListFiles Error: /ect/security/cacerts/: No such file or directory

**Comment by huitc** [comment]
原來你写错了。。。

**Comment by huitc** [comment]
放了之后重启也不行。。。😭

**Comment by MegatronKing** [comment]
抱歉，确实写错了，已纠正

**Comment by MegatronKing** [comment]
如果导入了还是不行，有两种情况：
1. 被抓App使用了自签证书，不需要经过CA校验，也就是说系统会自动校验App内置自签证书公钥和服务器私钥签名是否一致。这种情况下，由于HttpCanary根证书签的证书签名和App内置自签证书公钥签名不同，导致无法抓包，现象就是网络连接失败。
2. 被抓包App虽然使用了CA签发的证书，但是App自身对服务器证书签名做了校验，这种情况也会导致签名不一致校验失败，现象也是网络连接失败。
这两种情况，任何抓包应用都解决不了明文数据包，即真正安全无法抓包。一般前一种情况多一些。

**Comment by huitc** [comment]
所以无解了吗? ^^''

**Comment by arfaWong** [comment]
已 root，但是移动为系统证书失败，能怎么查原因吗？

**Comment by MegatronKing** [comment]
移动证书功能有bug，你先用mt等文件管理器手动移吧
