### ISSUE TITLE
关于HTTPCanary，我希望提一些建议

### ISSUE THREAD

**Issue by K85** [MegatronKing/HttpCanary#43]
几天前发现了HTTPCanary这款软件，确实做的不错，基本功能都全了，但是有些地方还是存在缺陷。

①想问下静态注入！能否支持动态URL。
像  http：//myserver/user_id/123456/profile？参数
这样的网址，如果中间的123456可以用正则表达式表示，就太好了

②能否支持导出和导入静态注入器。
我发现静态注入器存储在app.db中，HTTPCanary虽然本身不需要root，但是我想把我做的静态注入器分享给其他人使用，但其他人无法直接导入我做的静态注入器，他们只能通过访问data/data中HTTPCanary的数据，来覆盖app.db文件。而这样做，是需要root的。
能否做到不需要root，导出和导入静态注入器
另外，我注意到，静态注入器被视为一种插件，但却不存储在内置存储卡中，而放在data/data的应用数据下。我希望插件可以统一在内置存储路径下，这样就可以免去root，更加方便

③HTTPCanary把抓包历史都保存在app.db中，没用多久，就几千条抓包记录，app.db从100kb变成7mb，希望可以出个删除这些记录的功能

最后，希望HTTPCanary可以做的更好

**Comment by K85** [comment]
④插件管理中，静态注入器的启用和禁用，不是立即生效的，每次更改选项，都需要先停止抓包，然后再重新开始抓包。这个是特性吗

**Comment by K85** [comment]
嘿，我发现了你在掘金上写的一篇教程

**Comment by MegatronKing** [comment]
感谢老铁的建议！

1. 下个版本v3.0.0会支持。
2. 注入器导入和导出，还需要一段时间支持，可能要再等几个版本。
3. 历史记录可以在设置中一次性清理，也可以在历史记录页面按照session删除，也可以设置缓存时间自动删除超时的记录。
4. 注入器不支持立即生效，必须重启抓包，后续可能会优化。

**Comment by K85** [comment]
> 感谢老铁的建议！
> 
> 1. 下个版本v3.0.0会支持。
> 2. 注入器导入和导出，还需要一段时间支持，可能要再等几个版本。
> 3. 历史记录可以在设置中一次性清理，也可以在历史记录页面按照session删除，也可以设置缓存时间自动删除超时的记录。
> 4. 注入器不支持立即生效，必须重启抓包，后续可能会优化。
好的。
对了，我也遇到double http head的问题。抓取的http好像有问题。前几天一直没碰到，今天不知道为什么，突然就出现这个问题了。

**Comment by K85** [comment]
还有一个问题是，对https协议的抓取不稳定。有时候，抓的到http，但抓不到https。
奇怪的是，我的配置没什么问题。每次遇到只能抓http，不能抓https的时候。我能做的就是重启目标应用，或者重启HTTPCanary，不断尝试，然后有时问题就解决了，有时解决不了。这个bug触发不稳定

**Comment by K85** [comment]
> 还有一个问题是，对https协议的抓取不稳定。有时候，抓的到http，但抓不到https。
> 奇怪的是，我的配置没什么问题。每次遇到只能抓http，不能抓https的时候。我能做的就是重启目标应用，或者重启HTTPCanary，不断尝试，然后有时问题就解决了，有时解决不了。这个bug触发不稳定

**Comment by willshion** [comment]
求支持pc平台fiddler 联动 remote connect端口开放

**Comment by gmkbenjamin** [comment]
> > 感谢老铁的建议！
> > 
> > 1. 下个版本v3.0.0会支持。
> > 2. 注入器导入和导出，还需要一段时间支持，可能要再等几个版本。
> > 3. 历史记录可以在设置中一次性清理，也可以在历史记录页面按照session删除，也可以设置缓存时间自动删除超时的记录。
> > 4. 注入器不支持立即生效，必须重启抓包，后续可能会优化。
> >    好的。
> 
> ⑤对了，我也遇到double http head的问题。抓取的http好像有问题。前几天一直没碰到，今天不知道为什么，突然就出现这个问题了。
> 
> ⑥~还有一个问题是，对https协议的抓取不稳定。有时候，抓的到http，但抓不到https。 奇怪的是，我的配置没什么问题。每次遇到只能抓http，不能抓https的时候。我能做的就是重启目标应用，或者重启HTTPCanary，不断尝试，然后有时问题就解决了，有时解决不了。这个bug触发不稳定~
> 经过这两天尝试，发现自从我手动设置了dns服务器后，很少再出现捕捉不到https的问题。该问题基本上解决了

Hmmm... I'm still having issues capturing&decrypting https traffic even after I set DNS manually. Do I need to root the device and install CA certificate into the system store?
