### ISSUE TITLE
期待增加一键复制功能

### ISSUE THREAD

**Issue by a1369521908** [MegatronKing/HttpCanary#45]
期待增加一键复制返回值功能 : )

**Comment by huitc** [comment]
那個位置？

**Comment by MegatronKing** [comment]
具体应用场景是怎样的？有详细描述么

**Comment by a1369521908** [comment]
后台返回数据量多的时候,复制出来写文档 : )~

**Comment by a1369521908** [comment]
![image](https://user-images.githubusercontent.com/32727597/62507618-9d1ac480-b837-11e9-8e5b-47cfe1db9798.png)

**Comment by MegatronKing** [comment]
分享现在是支持QQ或者微信等的

**Comment by a1369521908** [comment]
![image](https://user-images.githubusercontent.com/32727597/62521025-62c61d00-b861-11e9-8b37-db3b0c88f52d.png)
没看到#捂脸
我的是安卓9.0的...
![image](https://user-images.githubusercontent.com/32727597/62521141-a6208b80-b861-11e9-9186-f176d8ff5b0f.png)

**Comment by MegatronKing** [comment]
QQ和微信不支持同时分享多个文件，请分别分享请求和响应

**Comment by a1369521908** [comment]
好的谢谢 ~
