### ISSUE TITLE
关于软件和组播/广播消息的疑惑

### ISSUE THREAD

**Issue by wqqqy** [MegatronKing/HttpCanary#47]
当我在测试该软件时，我同时利用wireshark进行抓包。
其中一个过程是app组播/广播 ssid（wifi名称）和passwd（WiFi密码）给一个iot设备，让iot脸上app所在的局域网，但是当开启该软件时，配网一直失败，wireshark也无法嗅探到广播的包。
关闭软件后即实现。
想请教一下，是否该软件无法实现组播/广播消息（因为vpn？）？谢谢。

**Comment by MegatronKing** [comment]
路由器相关交换协议，比如IGMP，ICMP协议都不支持转发，所以开了VPN后，这些协议消息无法通讯

**Comment by MegatronKing** [comment]
技术上是可以解决的，但是我一直没有时间去实现这些协议

**Comment by wqqqy** [comment]
好的，感谢你的回答~

**Comment by MegatronKing** [comment]
已经支持了ping，其它的暂不支持。
