### ISSUE TITLE
重發請求只有在啟用HttpCanary時有效

### ISSUE THREAD

**Issue by maple3142** [MegatronKing/HttpCanary#50]
如題
當我把HttpCanary的vpn關閉時按下重發應該也要有效果，但是實際上沒有
對於這個我覺得要嗎能讓它在不開HttpCanary下也能發vpn或是加一些提示告訴使用者需要啟用vpn才能重發請求

**Comment by MegatronKing** [comment]
关闭VPN的情况下，重发是生效的，只是不会显示在抓包列表里面。后面会加入到列表里面。

**Comment by MegatronKing** [comment]
已实现。
