### ISSUE TITLE
How to open the websocket history file .wscy?

### ISSUE THREAD

**Issue by saeedek** [MegatronKing/HttpCanary#53]
Hello,
I have captured some websocket traffic and when I save it, it saves it as .wscy
is there a way so I can open it on my computer?

Thanks

**Comment by MegatronKing** [comment]
wscy is a specific extension of HttpCanary, only can be opened by HttpCanary app.

**Comment by saeedek** [comment]
thanks,
just to piggyback of this thread, I have an issue on the opening the websocket history of previously captured data, when I open the websocket traffic, it forces the app to crash.

**Comment by MegatronKing** [comment]
Fixed on v3.1.3
