### ISSUE TITLE
Parallel Space crashes with Android 10

### ISSUE THREAD

**Issue by markcs** [MegatronKing/HttpCanary#57]
The only way I'm reliably able to capture packets is to use Parallel Space together with HttpCanary.

I know Parallel Space is not your app, but the version that is installed via HttpCanary no longer works on Android 10.

It simply crashes on startup.

**Comment by MegatronKing** [comment]
Parallel Space is no longer a SSL/TLS certificate solution on Android 10, the only solution is root your device and add the MITM certificate into system ca list.
