### ISSUE TITLE
In NetBare, how to modify a html page?

### ISSUE THREAD

**Issue by heyaustin** [MegatronKing/HttpCanary#58]
In NetBare, how to get the string format of body and modify the body then send out?
Thanks a lot.
https://github.com/MegatronKing/NetBare/issues/24

**Comment by MegatronKing** [comment]
1. Parse the response packets, maybe from a gzip/chunked encoding.
2. Modify the content and encode it as the origin encodings.
3. Send the new content with InjectorCallback.

**Comment by heyaustin** [comment]
Could you give me a code example?
Thank you

**Comment by heyaustin** [comment]
I've tried this:
`GZIPInputStream(HttpBodyInputStream(body)).bufferedReader(UTF_8).readText()`
which returns error:
`2019-09-09 15:12:56.961 28971-29286/com.github.megatronking.netbare.sample E/NetBare: Unexpected end of ZLIB input stream
    java.io.EOFException: Unexpected end of ZLIB input stream`

**Comment by MegatronKing** [comment]
The body may have multi frames.

**Comment by Ezreal147** [comment]
I have a similar problem,
Not in GZIP format,
I guess my body is too big,how to solve this problem?
