### ISSUE TITLE
Firefox certificate installation? 

### ISSUE THREAD

**Issue by eladkarako** [MegatronKing/HttpCanary#59]
how to?

**Comment by MegatronKing** [comment]
HttpCanary's Settings -> HttpCanary Root CA Settings -> Firefox

**Comment by eladkarako** [comment]
there is no such option.
<img src="https://i.imgur.com/jgzCfWql.jpg" />

**Comment by eladkarako** [comment]
anything like https://localhost:12345/certificate.crt will be fine as well, since this is the only way Firefox will accept the certificate (no way of installing from file:///)

**Comment by MegatronKing** [comment]
@eladkarako Did you install a firefox app with package name other than **org.mozilla.firefox**, I check this package name to determine whether the option is displayed.

**Comment by eladkarako** [comment]
I did used the Firefox nightly (developer/beta), 
https://www.apkmirror.com/apk/mozilla/firefox-nightly-for-developers/firefox-nightly-for-developers-68-2a1-release/
https://www.apkmirror.com/apk/mozilla/firefox-nightly-for-developers/firefox-nightly-for-developers-68-2a1-release/firefox-nightly-for-developers-68-2a1-52-android-apk-download/
which uses <code>org.mozilla.fennec_aurora</code>, 

but even if it is different, 
menu items may be better be 'grayed out' instead of invisible, 
this way I'll know there is an option, and where the problem is related to (identifying FF installation).
You may also provide an additional manual installation (or at least document it in the WiKi pages) for manual certificate installation with something like <code>http(s)://localhost:port/.../.../certificate.crt</code>....

**Comment by MegatronKing** [comment]
@eladkarako Try v3.1.4, I have added this feature.

**Comment by 687766616e** [comment]
tor browser也不行 beta ver?
