### ISSUE TITLE
使用root移动证书后依然不信任用户证书

### ISSUE THREAD

**Issue by Jkkoi** [MegatronKing/HttpCanary#60]
![Screenshot_2019-09-08-15-42-10-638_com guoshi httpcanary premium](https://user-images.githubusercontent.com/39653010/64485160-64637600-d24f-11e9-96b3-f8267ad81900.jpg)

**Comment by MegatronKing** [comment]
有具体用例吗

**Comment by Jkkoi** [comment]
> 有具体用例吗

新版本已经没有这个问题了23333333333  
感谢~~~

**Comment by Jkkoi** [comment]
> 有具体用例吗

新版本已经没有这个问题了23333333333  
感谢~~~
