### ISSUE TITLE
URL请求路径能正则吗？

### ISSUE THREAD

**Issue by XVNYATA** [MegatronKing/HttpCanary#61]
因为需要指定的URL进行处理，请作者更新吧，已在play支持作者了。

**Comment by MegatronKing** [comment]
您好，感谢支持！关于您的问题，URL的path可以使用通配符进行匹配。



---原始邮件---
发件人: "XVNYATA"<notifications@github.com&gt;
发送时间: 2019年9月14日(星期六) 晚上8:15
收件人: "MegatronKing/HttpCanary"<HttpCanary@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [MegatronKing/HttpCanary] URL请求路径能正则吗？ (#61)



因为需要指定的URL进行处理，请作者更新吧，已在play购买了。

**Comment by XVNYATA** [comment]
像这种带请求参数的链接
https://wx.b.com/userroll/userrolllist?classify_type=3&count=20&csrf_token=A&exportkey=B&sort_type=1
该如何匹配例如classify_type=3的链接呢，我试了几次都没成功。

**Comment by MegatronKing** [comment]
匹配的锚点是url的path，query parameters属于内容数据，不在匹配范围

**Comment by XVNYATA** [comment]
这种情况，现在该怎么操作，是不是下个版本才能实现？

**Comment by MegatronKing** [comment]
这个没有计划实现

**Comment by XVNYATA** [comment]
好吧，谢谢了，中秋快乐
