### ISSUE TITLE
代理冲突问题

### ISSUE THREAD

**Issue by dash-remi** [MegatronKing/HttpCanary#73]
请问如何在使用过httpcanary的同时使用VPN，目标APP必须过梯子

**Comment by kotori2** [comment]
刚发现这个问题，居然有人提了（
像surge之类支持前置代理，可以直接用socks5转发到电脑上，然后连电脑上的socks5服务器就好。希望有这样的功能

**Comment by tennc** [comment]
上级路由能访问google 就好了

**Comment by MegatronKing** [comment]
VPN冲突是系统问题，暂时没有解决方案。

**Comment by kotori2** [comment]
@MegatronKing 不是让httpcanary跟系统VPN同时开，而是让httpcanary连接前置代理。

**Comment by joostshao** [comment]
这个能解决吗？ 有思路吗？各位
