### ISSUE TITLE
CA证书移动到系统目录后，无法使用

### ISSUE THREAD

**Issue by yuzepeng** [MegatronKing/HttpCanary#77]
设备：小米MIX2 小米8（屏幕指纹版）。
前提条件：已root，system 分区解锁，确定已成功移动到系统目录

使用MIX2时，刚开始比较正常， 后来机会无法使用， 无法使用后我就重复打开或者重启手机偶尔可以用，但是 大部分情况无法使用，无法正常连接。
比较奇怪的是，我写了一个demo使用NetBare库，同样移动证书到系统，开启后就不会出现这个情况。

**Comment by MegatronKing** [comment]
每次非覆盖安装App或者重新生成证书都需要移到系统目录，可能是这个原因导致的
