### ISSUE TITLE
Using HTTPCanary via VPN

### ISSUE THREAD

**Issue by sxiii** [MegatronKing/HttpCanary#78]
Hi! I'm trying to make the HTTPCanary work via VPN. I've tried Windscribe and ZoogVPN. 

The issue is the same: when I start capturing, VPN disconnects right away. When I start VPN, canary stops getting data at the same time.

Is there anything to make it work?

Thanks

**Comment by dualriposte** [comment]
I m also trying to do the same thing from a geo restricted app ..and got the same results ....
hope something comes up.

Thanks

**Comment by uinanfan32** [comment]
You can use VPN on your router

**Comment by R13TechNewbie** [comment]
[This video](https://youtu.be/D3gOLCx38ks) show that http canary can run with http injector, which is both of them using vpn access to run with. But if I try that on my phone, it doesn't work. Any theory behind this about how it works? 

Is it because the device is rooted?

**Comment by MegatronKing** [comment]
System limitation, no solution.

**Comment by cloudexp** [comment]
Httpcanary installation vpn configuration buttion doesn't work.can install skip all free settings but there wearing some capture futures not available then.do any one know reason for this issue?
