### ISSUE TITLE
失败的请求可否显示完全请求信息

### ISSUE THREAD

**Issue by Songkeys** [MegatronKing/HttpCanary#79]
目前只能在 ⚠️ 里看到域名、解决方法`我也不知道啊`。希望可以显示详细的请求信息，比如请求的 URL、方法、参数等。

**Comment by MegatronKing** [comment]
这个一般是SSL/TLS加密数据解析问题，可能是证书信任等原因导致。由于无法解密数据包，所以获取不到请求的 URL、方法、参数等。
