### ISSUE TITLE
google play 里搜索不到了

### ISSUE THREAD

**Issue by mgiftdc** [MegatronKing/HttpCanary#83]
![image](https://user-images.githubusercontent.com/22900909/71655701-0238fe80-2d73-11ea-9367-45ff3a69347e.png)
在google play里搜索，出来的结果都不是这个。

**Comment by MegatronKing** [comment]
可能是地区的限制，试试这个：
https://play.google.com/store/apps/details?id=com.guoshi.httpcanary&hl=en_US
