### ISSUE TITLE
大佬，请问下，抓包的时候如何知道每个请求是来自于哪个app的？

### ISSUE THREAD

**Issue by scorpiokara** [MegatronKing/HttpCanary#84]

**Comment by MegatronKing** [comment]
Android Q（10）已经限制了/proc/net/的读取权限，无法获取了。其它版本可以，具体原理请移步：
https://github.com/MegatronKing/NetBare/blob/master/netbare-core/src/main/java/com/github/megatronking/netbare/net/UidDumper.java
