### ISSUE TITLE
满血满状态，继续更新HttpCanary啦！

### ISSUE THREAD

**Issue by MegatronKing** [MegatronKing/HttpCanary#87]
首先非常抱歉，由于前阵子压力过大，所以将HttpCanary的事情暂时完全抛出脑后。新的一年开始了，满血满状态原地复活！

下个版本已经在测试中，重构了部分逻辑，新增了一些小功能，期待再次与大家见面。

**Comment by Haleclipse** [comment]
捕获:smile:新年快乐吖

**Comment by yuzepeng** [comment]
加油 奥利给！！！

**Comment by 31415-hub** [comment]
请问怎么让httpcanary执行curl命令时自定义文件为请求体？能举个例子吗？还有现在激活版能买吗？

**Comment by 506494463** [comment]
如何下载
