### ISSUE TITLE
添加证书导入功能

### ISSUE THREAD

**Issue by Haleclipse** [MegatronKing/HttpCanary#9]
项目不错，更新也勤，已入正支持
提个建议，最近抓了下soul这个软件，通过justTrustMe来过掉证书验证有效，但服务器端响应的内容是400，没有发送ca证书，似乎像是https双向认证，post请求时带了证书，逆向看了下逻辑确实是用自有证书构造了关键的通信请求，据说可以将客户端证书附加到代理软件。
[JustTrustMe](https://github.com/WooyunDota/DroidSSLUnpinning)
![issue](https://i.loli.net/2019/03/29/5c9e00b5408dd.png)

**Comment by MegatronKing** [comment]
如果说客户端请求时带了公钥证书，这个就无解了。没有服务端的私钥证书，客户端和中间层伪造服务器SSL握手就会失败。

**Comment by MegatronKing** [comment]
抓包的流程是这样的。请求过程：客户端App -> 中间层Serve r -> 中间层Client -> 真正Server。如果客户端App带了公钥证书，中间层Server必须有私钥证书，不然第1步就连接失败，都不会走到后面2和3步。而导入App带的公钥证书，只能解决中间层Client -> 真正Server这个过程，即第3步。问题是1步都失败了，就没有后面2和3步了。

**Comment by MegatronKing** [comment]
我刚刚突然明白你的意思了，你是想通过justTrustMe来hook掉第1步，然后通过导入证书来解决第3步？这样吗？

**Comment by Haleclipse** [comment]
@MegatronKing 
是这样，如果说第一步都过不去的话，那只要在抓包环境下，客户端的请求应该是无法发出的，收到400响应是在客户端请求以后抓包软件里截获的一个网页内容，明确表示了`No required SSL certificate was sent` 
![](https://i.loli.net/2019/03/30/5c9f000acbfc8.png)
而在这种情况下客户端依旧收到了服务端发来的正确的数据。

**Comment by MegatronKing** [comment]
soul这个是双向验证，光有公钥还不行，还要有PKCS12证书的私钥口令。

**Comment by MegatronKing** [comment]
看走眼了，还是单向验证。没有带客户端公钥，带的是客户端PKCS12证书私钥，证书口令非常容易破解，这个安全机制做得真的是百密一疏。
回到正题，导入证书这个功能，技术上可以实现，但是比较复杂。一是，证书的类型有好几种。二是，双向都要做，工作量不小。

**Comment by Haleclipse** [comment]
@MegatronKing 
慢慢来吧，我也就随口一提。证书种类我是分不清楚，以前也是想把crt,cer之类的证书转成安卓系统的那种`*.0` 后来在电脑上用OpenSSL转的，看你实现了就挺有意思的

**Comment by Haleclipse** [comment]
关于证书，有没有什么文章推荐一下:wink:

**Comment by MegatronKing** [comment]
这个写的算是比较全的 https://juejin.im/post/5c66cc1e6fb9a049c84ffd12

**Comment by Haleclipse** [comment]
@MegatronKing 
谢谢呀(*°∀°)=3

**Comment by MegatronKing** [comment]
2.7.0版本已添加证书导入功能。设置-> SSL证书管理 -> 管理SSL证书导入 -> 点击按钮+导入。
