### ISSUE TITLE
谷歌高级版HttpCanary 3.2.1 2月7日版本里，高级重发出现bug。

### ISSUE THREAD

**Issue by Delyfeel** [MegatronKing/HttpCanary#90]
1.开启抓包，高级重发次数（例如100 200）会无数据返回。而且大概率卡住不再发送。
2.关闭抓包，高级重发次数（例如100 200）会无数据返回。而且大概率卡住不再发送。
1.开启抓包，高级重发次数（例如100 200），增加间隔（100），除了第一次有返回外其他次数无数据返回。
2.关闭抓包，高级重发次数（例如100 200），增加间隔（100）。有数据返回，但是有大概率卡住不再发送。
望修复！

**Comment by MegatronKing** [comment]
Fixed!
