### ISSUE TITLE
Please add url whitelist

### ISSUE THREAD

**Issue by olivierberten** [MegatronKing/HttpCanary#94]
I'm trying to debug an app that seems to have ssl pinning only on the authentification url. So I'd like to let that url skip the vpn instead of having to stop capture, do the authentification, and restart capture, missing a bunch of packages in the meantime...

**Comment by MegatronKing** [comment]
You can try blacklist which allows your host skip HttpCanary.

**Comment by olivierberten** [comment]
The point is the authentification url is on the same host as the rest...

**Comment by MegatronKing** [comment]
Url path data is in SSL/TLS encrypted packet, it is impossible to distinguish without decryption.

**Comment by olivierberten** [comment]
Wouldn't it be possible to send it again directly if it's in the white (or black, I don't know which concept fits better the situation) list?

**Comment by MegatronKing** [comment]
Very sorry, I think this is unsolvable.
