### ISSUE TITLE
谷歌版3.2.3或以上版本抓包无app头像

### ISSUE THREAD

**Issue by 122cygf** [MegatronKing/HttpCanary#95]
如题，收藏界面也没有。之前版本是正常的
![Screenshot_2020-03-08-12-25-18-497_com guoshi httpcanary premium](https://user-images.githubusercontent.com/55302758/76166282-73909580-6198-11ea-869a-8db2b5ed72ba.jpg)

**Comment by MegatronKing** [comment]
3.2.5已修复
