### ISSUE TITLE
Support for client SSL certificate authentication

### ISSUE THREAD

**Issue by BruceZhang1993** [MegatronKing/HttpCanary#98]
- Add ability to import PK#12,BKS,etc file w/o password
- Add ability to set host and port to enable client ssl cert

**Comment by MegatronKing** [comment]
Settings -> SSL Certificate Manager -> Add

**Comment by BruceZhang1993** [comment]
Thanks. I missed that. 😶

**Comment by MegatronKing** [comment]
In fact this feature is lacking in testing, if you have any issue or good idea, please tell me.
